apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

patchesStrategicMerge:
  - patch.yaml

images:
  - name: alya-backend
    newName: localhost:5000/alya-backend
    newTag: latest

configMapGenerator:
  - name: alya-config
    behavior: merge
    literals:
      - env=development
      - log_level=debug
