apiVersion: apps/v1
kind: Deployment
metadata:
  name: alya-backend
  namespace: alya
spec:
  replicas: 1
  template:
    spec:
      containers:
        - name: alya-backend
          resources:
            limits:
              cpu: "500m"
              memory: "256Mi"
            requests:
              cpu: "100m"
              memory: "128Mi"
