apiVersion: v1
kind: Service
metadata:
  name: token
spec:
  type: ClusterIP
  selector:
    app: token
  ports:
    - port: 5003
      targetPort: 8083
      name: token
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: token-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: token
  template:
    metadata:
      labels:
        app: token
    spec:
      containers:
        - name: token
          image: token
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: 500m
          ports:
            - containerPort: 8083
              name: http
