apiVersion: apps/v1
kind: Deployment
metadata:
  name: alya-backend
  namespace: alya
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: alya-backend
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
