apiVersion: v1
kind: ConfigMap
metadata:
  name: alya-config
  namespace: alya
data:
  env: "production"
  log_level: "info"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: alya-config-file
  namespace: alya
data:
  config.json: |
    {
      "server": {
        "port": 8080,
        "host": "0.0.0.0",
        "timeout": "30s",
        "cors": {
          "allowedOrigins": ["*"],
          "allowedMethods": ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
          "allowedHeaders": ["Content-Type", "Authorization"],
          "allowCredentials": false,
          "maxAge": 300
        },
        "tlsEnabled": false
      },
      "cache": {
        "type": "redis",
        "address": "alya-redis:6379",
        "ttl": "24h"
      },
      "logger": {
        "level": "info",
        "enableJson": true,
        "enableTime": true,
        "enableCaller": true,
        "disableColors": true
      }
    }
