apiVersion: apps/v1
kind: Deployment
metadata:
  name: alya-backend
  namespace: alya
  labels:
    app: alya-backend
    app.kubernetes.io/name: alya-backend
    app.kubernetes.io/part-of: alya
spec:
  replicas: 2
  selector:
    matchLabels:
      app: alya-backend
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: alya-backend
    spec:
      containers:
        - name: alya-backend
          image: alya-backend:latest # Will be overridden in overlays
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
          resources:
            limits:
              cpu: "1"
              memory: "512Mi"
            requests:
              cpu: "200m"
              memory: "256Mi"
          env:
            - name: ALYA_ENV
              valueFrom:
                configMapKeyRef:
                  name: alya-config
                  key: env
            - name: ALYA_SERVER_PORT
              value: "8080"
            - name: ALYA_DB_HOST
              value: "alya-postgres"
            - name: ALYA_DB_PORT
              value: "5432"
            - name: ALYA_DB_USER
              value: "postgres"
            - name: ALYA_DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: alya-secrets
                  key: db-password
            - name: ALYA_DB_NAME
              value: "alya"
            - name: ALYA_YOUTUBE_API_KEY
              valueFrom:
                secretKeyRef:
                  name: alya-secrets
                  key: youtube-api-key
            - name: ALYA_AI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: alya-secrets
                  key: ai-api-key
            - name: ALYA_CACHE_TYPE
              value: "redis"
            - name: ALYA_CACHE_ADDRESS
              value: "alya-redis:6379"
            - name: ALYA_LOG_LEVEL
              valueFrom:
                configMapKeyRef:
                  name: alya-config
                  key: log_level
          volumeMounts:
            - name: config-volume
              mountPath: /app/config
          livenessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              path: /health
              port: http
            initialDelaySeconds: 5
            periodSeconds: 5
            timeoutSeconds: 3
            failureThreshold: 2
      volumes:
        - name: config-volume
          configMap:
            name: alya-config-file
