apiVersion: v1
kind: Service
metadata:
  name: alya-backend
  namespace: alya
  labels:
    app: alya-backend
    app.kubernetes.io/name: alya-backend
    app.kubernetes.io/part-of: alya
spec:
  selector:
    app: alya-backend
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
